### ISSUE TITLE
state load is not working at Super Nintendo emul

### ISSUE THREAD

**Issue by gozz6270** [shantigilbert/Sx05RE#105]
Hello. I'm not good at english. so I want you to understand my odd sentence.

I want to save and load state at super nintendo emul.
I could save and load state other all emul, but super nintendo.
save is well done at super nintendo emul too. but when I load state, emul off and out to game select screen.
(I could find files that I saved in root/storage/statesaves folder)
how can I solve this problem?

**Comment by shantigilbert** [comment]
I can confirm this, it seems to be an issue with Snex9x 2010 as it works with Snes9x

In the meantime you can edit es_systems.cfg 

```
<system>
		<name>snes</name>
		<fullname>Super Nintendo</fullname>
		<path>/storage/roms/snes</path>
		<extension>.smc .SMC .fig .FIG .sfc .SFC .gd3 .GD3 .gd7 .GD7 .dx2 .DX2 .bsx .BSX .swc .SWC .zip .ZIP</extension>
		<command>/usr/bin/retroarch -L /tmp/cores/snes9x_libretro.so %ROM%</command>
		<platform>snes</platform>
		<theme>snes</theme>
	</system>
```

**Comment by gozz6270** [comment]
very nice. I solve it for your help.
I'm impressed of your knowledge.

Thank you so much for your support.
