### ISSUE TITLE
how to record video in sx05re?

### ISSUE THREAD

**Issue by gozz6270** [shantigilbert/Sx05RE#111]
I found recording tap in sx05re config menu.
I did on it(recording option) and load contents for recording.
after close contents, I tried to find making video files. 
but I could not find it. 

recording function originally is not working in sx05re?

**Comment by shantigilbert** [comment]
Sorry I don't understand what you just said, do you mean recording in retroarch??

**Comment by gozz6270** [comment]
ah~ can't recording video(game playing video) in the sx05re without other hardware?

**Comment by shantigilbert** [comment]
Retroarch has a function to record video, but I have no idea if it works on
Amlogic boxes.

**Comment by gozz6270** [comment]
ok. I understand.
I appreciate your rapid reply. thank you very much! ^0^
