### ISSUE TITLE
Sx05RE 1.8.5 cant boot on MXQ pro 4k

### ISSUE THREAD

**Issue by Kokokool** [shantigilbert/Sx05RE#116]
hi, few questions

1. Sx05RE 1.8.5 cant boot on MXQ pro 4k but Scottelec 1.8.3 was succesfully booted from sd without changing the dtb. 
any guess? dtb impact here?

2. since im using Scottelec 1.8.3 as stated above, I seriously need to boot the machine into ES directly, not kodi.
I know theres a way to solve this by modifying autostart.sh but the latest three lines says this:

**if you don't want the emulator front end to start first, comment the next 3 lines
 #rm -rf /var/lock/start.kodi
 #/usr/bin/startfe.sh &_** 

if I remove the # it boots the same way.

Please helpme on this.
Regards

**Comment by shantigilbert** [comment]
I am not familiar with any changes that Scottelec has made, sorry. But if you run the version I provide then you do need to use the proper DTB, my version runs ES.

You can find the DTB that works on this version on the following link.
https://kszaq.libreelec.tv/s905/8.2/device_trees/

**Comment by Kokokool** [comment]
Perfect, i'll try those and ill let you know.
Perhaps your 1.8.5 build was using a DTB from a different box than mine.

Take care, thanks

**Comment by shantigilbert** [comment]
Yes I do not own a MXQ, thats why I always suggest people get the proper DTB :) 

I am closing this issue now, if you have any other problems feel free to reopen it.
