### ISSUE TITLE
Can't start with parallel64(Nin64)

### ISSUE THREAD

**Issue by PYTHONKOR** [shantigilbert/Sx05RE#117]
I was set parallel64 in Mainmenu.("parallel-n64")
but Can't start Game. So I was found error.

-----------------------------------
File = Sx05RE-Sx05RE_8.2\packages\sx05re\emulationstation\patches\emulationstation-02-Sx05RE.patch
Line 96 =  n64choices.push_back("parallel-n64");
-----------------------------------

It is happened bacause of '.so' file is start with 'parallel_n64'.
I hope you will fix it.

Thanks.

**Comment by shantigilbert** [comment]
Doh! will fix asap! thanks for the report!

**Comment by shantigilbert** [comment]
Fixed on latest release
