### ISSUE TITLE
About the cheats problem of RetroArch?

### ISSUE THREAD

**Issue by ji125443** [shantigilbert/Sx05RE#120]
After 1.8.2, this function is gone. This function is very important, for example: PS1 NES SNES MD can use this function!

**Comment by shantigilbert** [comment]
Cheats have not been disabled as far as I know but In order to reduce size, libretro-database is not included anymore, if its needed it can always be installed  from Retroarch.

**Comment by ji125443** [comment]
I have installed the libretro database, but there is still no cheating option in the core shortcut menu, and I would like to add this option in the next version

**Comment by shantigilbert** [comment]
I will retry installing it manually to see if it works, it worked fine when I tested it before. 

I am trying to steer clear of putting it back by default because it adds about 200mb to the final image and its something that its not really needed (besides from the cheats I guess).

**Comment by shantigilbert** [comment]
Cheat are enabled again on latest release, you need to download the cheats from the RA menu. 

https://github.com/shantigilbert/Sx05RE/releases/tag/v1.8.6_bf
